# These are supported funding model platforms

github: [cortexrd, CharlesBrunelleIO, CSWinnall]
custom: ['https://www.paypal.com/donate/?hosted_button_id=5JU6CKPCMMDZL', 'https://www.buymeacoffee.com/awtej7undz/knack-toolkit-library-support']
