var ktlFeatures = {
    showAppInfo: false,
    showKtlInfo: false,
    showMenuInTitle: false,
    selTextOnFocus: false,
    inlineEditColor: false,
    rowHoverHighlight: false,
    chznBetter: false,
    autoFocus: false,
    sortedMenus: false,
    userFilters: false,
    persistentForm: false,
    calendarGotoDate: false,
    rememberMe: false,
    formPreValidation: false,
    spinnerWatchDog: false,
    idleWatchDog: false,
    debugWnd: false,
}
